spring:
  datasource:
    url: jdbc:h2:mem:gymdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    user:
      name: dev
      password: dev
    basic:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# H2 Web Console
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
